---
# Add needed repositories and install packages
- name: Install package apache
  ansible.builtin.package:
    name: "{{ '{{' }} {{ cookiecutter.rolename_slug}}_packagename {{ '}}' }}"
    state: present
