---
# set variables for different OS families
- name: "Set {{ '{{' }} ansible_os_family {{ '}}' }}-specific variables"
  ansible.builtin.include_vars: "{{ '{{' }} ansible_os_family | lower {{ '}}' }}.yml"

# Check prequisites
- name: Pre-flight checks
  ansible.builtin.include_tasks: preflight.yml

# Install package
- name: Install needed packages
  ansible.builtin.include_tasks: install_packages.yml

# Configure package
- name: Configure package
  ansible.builtin.include_tasks: configure_packages.yml

# Configure services
- name: Configure services
  ansible.builtin.include_tasks: configure_services.yml
