# converge.yml is responsible for running the role itself
---
- name: Converge
  hosts: all
  tasks:
    - name: "Test {{ cookiecutter.rolename }}"
      ansible.builtin.include_role:
        name: '{{ cookiecutter.rolename_slug }}'
      vars:
        # pass var to let the role know it's being run in a molecule test
        {{ cookiecutter.rolename_slug}}_in_molecule_test_run: True
