# converge.yml is responsible for running the role itself
---
- name: Converge
  hosts: all
  tasks:
    - name: "Test {{ cookiecutter.rolename }}"
      ansible.builtin.include_role:
        name: '{{ cookiecutter.rolename_slug }}'
      vars:
        in_molecule_test_run: true
