
---
- name: Check if nginx is installed and running
  hosts: all
  gather_facts: no
  tasks:
    - name: Check if nginx is installed
      command: which nginx
      register: nginx_installed
      failed_when: nginx_installed.rc != 0

    - name: Check if nginx is running
      command: systemctl is-active nginx
      register: nginx_running
      failed_when: nginx_running.stdout != "active"